### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by clabnet** [Dawntraoz/cabbage#4]
Hi, 
cloned this repository, Win10, 

```
D:\Weblabs\cabbage>node -v
v14.17.0

D:\Weblabs\cabbage>npx -v
6.14.13

yarn 
yarn dev
http://localhost:3000 
401 Unauthorized
```

Why ? 
Thanks

**Comment by clabnet** [comment]
The problem is here.

```
'storyblok-nuxt',
      {
        accessToken: process.env.API_KEY,
        cacheProvider: 'memory',
      },
```
I know because the .env is not found on repository.

Can I remove the call to storyblok to run the template without it ?

**Comment by Dawntraoz** [comment]
Hi @clabnet, to make this demo work you will need to create your own space in Storyblok following the series that explain it, starting from this one: https://www.dawntraoz.com/blog/create-a-dashboard-with-tailwindcss-adding-storyblok/ 

And add your Storyblok token in the .env variable API_KEY.

**Comment by Dawntraoz** [comment]
I have now also added this information to the Readme.md to avoid possible confusion.

Thank you very much for creating the issue and for letting me know if you need help setting up your space or just wanted to extract the design of the application, let me know, and I will be happy to help you.
